package model

case class DataISIN(id:String,
                secid:String,
                shortname:String,
                regnumber:String,
                name:String,
                isin:String,
                is_traded:String,
                emitend_id:String,
                emitent_title:String,
                emitent_inn:String,
                emitent_okpo:String,
                gosreg:String,
                _type:String,
                group:String,
                primary_boardid:String,
                marketprice_boardid:String)
case class DataStock(boardid : String,
                     tradedate : String,
                     shortname: String,
                     secid:String,
                     numtrades:String,
                     value:String,
                     open:String,
                     low:String,
                     high:String,
                     legalcloseprice:String,
                     waprice:String,
                     close:String,
                     volume:String,
                     marketprice2:String,
                     marketprice3:String,
                     admittedquote:String,
                     mp2valtrd:String,
                     marketprice3tradesvalue:String,
                     admittedvalue:String,
                     waval:String
                    )
case class DataCandles(open: String,
                       close: String,
                       high: String,
                       low: String,
                       value: String,
                       valume: String,
                       begin: String,
                       end: String
                      )